[project]
name = "chord_app"
version = "0.1.0"
description = "Diatonic chord utility iOS app with Flet"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flet[all]>=0.28.3",
    "numpy>=1.26.0",
    "scipy>=1.11.0",
]
